DROP TABLE IF EXISTS tbl_consumers;

CREATE TABLE tbl_consumers (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  full_name VARCHAR(250) NOT NULL,
  rfc VARCHAR(15) NOT NULL,
  phone_number VARCHAR(15) NOT NULL,
  email VARCHAR(100) NOT NULL
);
